name: Entrega Contínua com GCP

on:
  workflow_call:

jobs:

  GCP_CloudRun:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GOOGLE_PROJECT }}
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Login to GCP
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.GOOGLE_PROJECT }}
    
      # gcloud configure docker
      #- name: Configure Docker
       # run: gcloud auth configure-docker --quiet

      # Build Docker image
     # - name: Build Docker image
     #   run: docker build -t $IMAGE_NAME .

      # Tag Docker image with GCR URI
     # - name: Tag Docker image
     #   run: docker tag $IMAGE_NAME $IMAGE_NAME

      # Push Docker image to Container Registry
    #  - name: Push Docker image
    #    run: docker push hugorebonato/go_ci:latest

      # Deploy Docker image to Cloud Run
      - name: Deploy Docker image to Cloud Run
        run: gcloud run deploy site --image hugorebonato/go_ci:latest --region us-central1 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 80
