name: Entrega Contínua com GCP

#on:
#  push:
#    branches: [Projeto_inicial]
    
#jobs:
#  deploy:
#    name: GCP_CloudRun
#    runs-on: ubuntu-latest
#    environment: prd

on:
  workflow_call:

jobs:
  Deploy_GPC_CloudRun:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GOOGLE_PROJECT }}/imagem:latest
    steps:    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
    # Artifact name
        name: programa
       
      # Git checkout
    - name: Checkout
      uses: actions/checkout@v4

    # Login to GCP
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.GOOGLE_PROJECT }}

    - name: Build and push Docker images  
      uses: docker/build-push-action@v3.0.0
      with:
    # Build's context is the set of files located in the specified PATH or URL
        context: .
    # Path to the Dockerfile
        file: ./Dockerfile
    # Push is a shorthand for --output=type=registry
        push: true
    # List of tags
        tags: $IMAGE_NAME
    
   # Push Docker image to Container Registry
    - name: Push Docker image
      run: docker push $IMAGE_NAME





    # Deploy Docker image to Cloud Run
    - name: Deploy Docker image to Cloud Run
      run: gcloud run deploy site --image $IMAGE_NAME --region us-central1 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 80
